name: Build and Push Multi-Arch Docker Image of Base-Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version to build'
        required: false
        default: '8.4.6'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set PHP_VERSION with a default value
      - name: Set PHP Version
        run: echo "PHP_VERSION=${{ github.event.inputs.php_version || '8.4.6' }}" >> $GITHUB_ENV

      # Build and push the multi-arch Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}
          tags: |
            tkrauseiuk/lageboard_base:latest
            tkrauseiuk/lageboard_base:${{ env.PHP_VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=registry,ref=tkrauseiuk/lageboard_base:latest
          cache-to: type=inline